name: Clone Public Repo

on: 
  workflow_dispatch:
    inputs:
      newRepoName:
        description: 'Fill the repository name: e.g. slack-connector'
        required: false

jobs:
  create-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create new repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_NAME="${{ github.event.inputs.newRepoName }}"
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/repos \
            -d "{\"name\":\"$REPO_NAME\", \"description\":\"A new repository created by GitHub Actions\"}"