name: Create Repository

on:
  workflow_dispatch:

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create a new repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request POST \
          --url "https://api.github.com/user/repos" \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer $GH_TOKEN" \
          --data '{"name": "new-repo", "private": false}'