name: Introduce new product

on: 
  workflow_dispatch:
    inputs:
      productName:
        description: 'Fill product name: e.g.slack-connector'
        required: true
      groupId:
        description: 'Fill groupId of product com.axonivy.connector.<myconnector> or com.axonivy.utils.<myutil>: e.g. com.axonivy.connector.slack'
        required: true
      version:
        description: 'Fill the ivy version which you use for developing: e.g. 12.0.0'
        required: true
      shortDescription:
        description: 'Fill short description of product:'
        required: false

permissions:
  contents: read

jobs:
  raise-products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Update Maven property
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.version }}-SNAPSHOT -DgenerateBackupPoms=false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update ${{ github.event.inputs.productName }} to ${{ github.event.inputs.version }}"
          branch: update-${{ github.event.inputs.productName }}-${{ github.event.inputs.version }}
          title: "Update ${{ github.event.inputs.productName }} to ${{ github.event.inputs.version }}"
          body: |
            This PR updates **${{ github.event.inputs.productName }}** to `${{ github.event.inputs.version }}` in all `pom.xml` files.
          labels: dependencies, automated-pr
          delete-branch: true