name: Introduce new product

on: 
  workflow_dispatch:
    inputs:
      productName:
        description: 'Fill product name: e.g.slack-connector'
        required: true
      groupId:
        description: 'Fill groupId of product com.axonivy.connector.<myconnector> or com.axonivy.utils.<myutil>: e.g. com.axonivy.connector.slack'
        required: true
      version:
        description: 'Fill the ivy version which you use for developing: e.g. 12.0.0'
        required: true
      shortDescription:
        description: 'Fill short description of product:'
        required: false

permissions:
  contents: read

jobs:
  raise-products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Update Maven property
        run: |
          find . -type f -exec sed -i 's|MY-PRODUCT-NAME|${{ github.event.inputs.productName }}|g' {} +
          find . -type f -exec sed -i 's|<version>12.0.0-SNAPSHOT</version><!-- identicate your minimal compliant ivy version with the first 2 digits -->|<version>${{ github.event.inputs.version }}</version>|g' {} +
          find . -type f -exec sed -i 's|MY-GROUP-ID|${{ github.event.inputs.groupId }}|g' {} +

      - name: Create Pull Request
        run: |
          BRANCH="replace-text-${{ github.run_id }}"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "chore: replace text"
          git push origin "$BRANCH"
          gh pr create --title "Test" --assignee "$GITHUB_ACTOR"