name: Introduce new product

on: 
  workflow_dispatch:
    inputs:
      productType:
        description: 'Which type are you implementing?'
        required: true
        type: choice
        options:
          - connector
          - utils
          - demo
      productName:
        description: |
          Fill your product name. The name must end with the product type selected above. Example: google-mail-connector | google-mail-utils | google-mail-demo
        required: true
      version:
        description: 'Fill the ivy version which you use for developing. Example: 12.0.0'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  initiate-product:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs only on the master branch"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Rename folder MY-PRODUCT-NAME-product to ${{ github.event.inputs.productName }}-product
        run: |
          mv MY-PRODUCT-NAME-product ${{ github.event.inputs.productName }}-product

      - name: Update name, groupId, artifactId, version, document
        run: |
          productName="${{ github.event.inputs.productName }}"
          productType="${{ github.event.inputs.productType }}"
          # 1. Remove productType at the end
          groupId="com.axonivy.$productType.${productName/%-${productType}}"
          # 2. Replace all '-' with '.'
          groupId="${groupId//-/.}"
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i "s|MY-PRODUCT-NAME|${{ github.event.inputs.productName }}|g" {} +
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i "s|<version>12.0.0-SNAPSHOT</version>|<version>${{ github.event.inputs.version }}-SNAPSHOT</version>|g" {} +
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i "s|MY-GROUP-ID|$groupId|g" {} +
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i "s|REPO-NAME|${{ github.event.repository.name }}|g" {} +
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i "s|<groupId>com.axonivy.market</groupId>|<groupId>$groupId</groupId>|g" {} +
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i 's|<!-- fill your product name -->||g' {} +
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i 's|<!-- fill your product name + a "-modules" postfix -->||g' {} +
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i 's|<!-- fill your product name + a "-product" postfix e.g. my-connector-product -->||g' {} +
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i 's|<!-- identicate your minimal compliant ivy version with the first 2 digits -->||g' {} +
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i 's|<!-- your group id: e.g. com.axonivy.connector.<myconnector> or com.axonivy.utils.<myutil> -->||g' {} +

      - name: Create new branch
        run: |
          BRANCH="introduce-new-product-${{ github.event.inputs.productName }}"
          git checkout -b "$BRANCH"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Initial new product ${{ github.event.inputs.productName }}"
          git push origin "$BRANCH"